/**
 * ============================================
 * TMS Mobile App - API Configuration
 * ============================================
 * 
 * This file is AUTO-GENERATED by the setup script.
 * DO NOT edit manually - your changes will be lost!
 * 
 * To reconfigure: Run `npm run setup-api` in TMS-MobileApp folder
 */

export const API_CONFIG = {
  apiUrl: 'http://192.168.76.186:5191'
};
